from app.schemas.common import ApiResponse, ErrorResponse, PaginatedResponse
from app.schemas.proxy import (
    ProxyConfigCreate,
    ProxyConfigResponse,
    ProxyConfigUpdate,
    ProxyTestRequest,
    ProxyTestResponse,
)
from app.schemas.task import (
    DownloadTaskCreate,
    DownloadTaskResponse,
    DownloadTaskUpdate,
    TelegramUploadResponse as TaskTelegramUploadResponse,
)
from app.schemas.tweet import (
    MediaUrl,
    TweetCreate,
    TweetFetchParams,
    TweetInDB,
    TweetSyncResult,
    TweetWithMedia,
    TwitterUserCreate,
    TwitterUserInDB,
)
from app.schemas.twitter import (
    MediaFileResponse,
    TweetResponse,
    TwitterAccountCreate,
    TwitterAccountResponse,
    TwitterAccountUpdate,
    TwitterOAuthCallback,
    TwitterUserResponse,
)
from app.schemas.user import (
    Token,
    TokenPayload,
    UserCreate,
    UserLogin,
    UserResponse,
    UserUpdate,
)
from app.schemas.telegram import (
    TelegramConfigCreate,
    TelegramConfigResponse,
    TelegramUploadCreate,
    TelegramUploadResponse,
    TelegramChatInfo,
    TelegramTestResponse,
    TelegramUploadResult,
    TelegramBatchUploadCreate,
    TelegramBatchUploadResult,
    TelegramUploadDetailResponse,
    UploadStatus,
)

__all__ = [
    "ApiResponse",
    "ErrorResponse",
    "PaginatedResponse",
    "DownloadTaskCreate",
    "DownloadTaskResponse",
    "DownloadTaskUpdate",
    "TaskTelegramUploadResponse",
    "MediaFileResponse",
    "MediaUrl",
    "TweetCreate",
    "TweetFetchParams",
    "TweetInDB",
    "TweetResponse",
    "TweetSyncResult",
    "TweetWithMedia",
    "TwitterAccountCreate",
    "TwitterAccountResponse",
    "TwitterAccountUpdate",
    "TwitterOAuthCallback",
    "TwitterUserCreate",
    "TwitterUserInDB",
    "TwitterUserResponse",
    "Token",
    "TokenPayload",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "UserUpdate",
    "ProxyConfigCreate",
    "ProxyConfigResponse",
    "ProxyConfigUpdate",
    "ProxyTestRequest",
    "ProxyTestResponse",
    "TelegramConfigCreate",
    "TelegramConfigResponse",
    "TelegramUploadCreate",
    "TelegramUploadResponse",
    "TelegramChatInfo",
    "TelegramTestResponse",
    "TelegramUploadResult",
    "TelegramBatchUploadCreate",
    "TelegramBatchUploadResult",
    "TelegramUploadDetailResponse",
    "UploadStatus",
]
